# Generated by Django 2.2.4 on 2023-03-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='painting',
            name='users_who_purchased',
            field=models.ManyToManyField(related_name='purchased_paintings', to='app1.User'),
        ),
    ]
